In [ ]:
#this notebook dicusses logistic regression implementation in python

In [108]:
import numpy as np

In [143]:

class LogisticRegression:
    def initial_Weights(self,features): 
        extra_column=np.ones((len(features),1))#add an extra columns on feature matrix for the bias
        np.concatenate((extra_column, features), axis=1)
        weights=np.random.randn(1,features.shape[1])#Genarate the initial weights
        return weights
    def compute_z(self,weights,features):#compute z values
        z=weights[0][0:1]+np.dot(weights[0][1:],features[:,1:].transpose())
        return z
    def estimate_of_y_via_sigmoid(self,z):#estimate the target i.e y_estimate
        y_estimate=1/(1+np.exp(-z))
        return y_estimate
    def derivative(self,y_estimate,y,features):#derivative of Logistic cost function i.e gradient_descent
        derivatives=np.dot((y_estimate-y).transpose(),features)
        derivatives=derivatives/len(features)
        return derivatives
    def adjusting_weights(self,weights,derivative,rate):#convergence of weights
        weights= weights-(rate*derivative)
        return weights
    def predict_category(self,y_estimate,threshold):#classification 
        predict=[]
        for i in y_estimate:
            if(i<threshold):
                predict.append(0)
            elif(i>=threshold):
                predict.append(1)
        return predict
    def accuracy(self,predicted_labels, actual_labels):
            diff = predicted_labels - actual_labels
            return 1.0 - (float(np.count_nonzero(diff)) / len(diff))

In [42]:
#loading the data file
import pandas as pd
flowers=pd.read_csv('IRIS.csv')

In [147]:
#sample 10 rows
flowers.head(10)

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1
5           5.4          3.9           1.7          0.4        1
6           4.6          3.4           1.4          0.3        1
7           5.0          3.4           1.5          0.2        1
8           4.4          2.9           1.4          0.2        1
9           4.9          3.1           1.5          0.1        1

In [152]:
#check if there is a null value in the dataset
flowers.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [45]:
#splitting the data into training and test data ratio of 8:2
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(flowers, test_size=0.2, random_state=42)

In [46]:
#create features by dropping the label
train_set_features=flowers.drop('species',axis=1)

In [150]:
train_set_features

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [47]:
#create the labels
train_set_labels=flowers['species'].copy()

In [151]:
train_set_labels

0      1
1      1
2      1
3      1
4      1
      ..
145    0
146    0
147    0
148    0
149    0
Name: species, Length: 150, dtype: int64

In [81]:
#convert the labels into a list
labels=train_set_labels.values

In [50]:
#scaling the features. This helps to avoid outliers( small and large values) influencing the model
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
features=scaler.fit_transform(train_set_features)

In [154]:
features.shape

(150, 4)

In [184]:
model=LogisticRegression()

In [185]:
weights=model.initial_Weights(features)

In [175]:
weights

array([[ 0.55474271,  0.84820999, -0.40978919,  0.26640039]])

In [73]:
z_value=model.compute_z(weights,features)

In [159]:
estimate=model.estimate_of_y_via_sigmoid(z_value)

In [82]:
derivativex=model.derivative(estimate,labels,features)

In [84]:
weights=model.adjusting_weights(weights,derivativex,0.01)

In [186]:
for x in range(1000):
    z_value=model.compute_z(weights,features)
    estimate=model.estimate_of_y_via_sigmoid(z_value)
    derivativex=model.derivative(estimate,labels,features)
    weights=model.adjusting_weights(weights,derivativex,0.01)

In [188]:
predictions=model.predict_category(estimate,0.5)
        

In [189]:
acc=model.accuracy(predictions, labels)

In [190]:
acc

1.0

In [214]:
labels

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1])

In [109]:
 extra_column=np.ones((4,1))#a

In [117]:
x=np.random.normal(size=(2,3))

In [118]:
y=np.random.normal(size=(1,3))

In [119]:
y

array([[-0.06850904, -0.46455931, -1.27905088]])

In [120]:
x

array([[-0.69363963,  0.54035216,  0.1944629 ],
       [ 0.84361184, -1.03409914, -0.34321229]])

In [124]:
 f=np.concatenate((x, y), axis=0)

In [125]:
train_set_features

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [156]:
features.shape[1]

4

In [134]:
weights=np.random.randn(1,len(features[0]))

In [135]:
weights

array([[ 0.45807125, -0.58659819, -1.08171953, -0.41338754]])

In [139]:
 weights[0][0:1]

array([0.45807125])

In [178]:
weights

array([[0.52647018, 0.41579937, 0.2629605 , 1.31014926]])

In [192]:
test_set_features=test_set.drop('species',axis=1)

In [193]:
test_set_features

sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4
31            5.4          3.4           1.5          0.4
64            5.6          2.9           3.6          1.3
141           6.9          3.1           5.1          2.3
68            6.2          2.2           4.5          1.5
82            5.8          2.7           3.9          1.2
110           6.5          3.2           5.1          2.0
12            4.8          3.0           1.4          0.1
36            5.5          3.5           1.3          0.2
9             4.9          3.1           1.5          0.1
19            5.1          3.8           1.5          0.3
56            6.3          3.3           4.7          1.6
104           6.5          3.0           5.8          2.2
69            5.6          2.5           3.9          1.1
55            5.7          2.8           4.5          1.3
132           6.4          2.8           5.6          2.2
29            4.7          3.2           1.6          0.2
127           6.1          3.0           4.9          1.8
26            5.0          3.4           1.6          0.4
128           6.4          2.8           5.6          2.1
131           7.9          3.8           6.4          2.0
145           6.7          3.0           5.2          2.3
108           6.7          2.5           5.8          1.8
143           6.8          3.2           5.9          2.3
45            4.8          3.0           1.4          0.3
30            4.8          3.1           1.6          0.2

In [194]:
scaled_test=scaler.fit_transform(test_set_features)

In [201]:
scaled_test.shape

(30, 4)

In [197]:
test_labels=test_set['species'].copy()

In [203]:
labels=test_labels.values

In [204]:
labels

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1])

In [205]:
z_value=model.compute_z(weights,scaled_test)
estimate=model.estimate_of_y_via_sigmoid(z_value)

  

In [206]:
estimate

array([0.12451779, 0.99793354, 0.00219143, 0.16852791, 0.09640443,
       0.99065039, 0.38913276, 0.10527146, 0.01134029, 0.18198407,
       0.18858068, 0.96769201, 0.99579809, 0.97593566, 0.99833166,
       0.43546856, 0.03877144, 0.09679506, 0.13870742, 0.02152752,
       0.98046045, 0.13180511, 0.98960338, 0.02351064, 0.40340616,
       0.06553116, 0.00738215, 0.06995754, 0.96155415, 0.97083852])

In [210]:
predicted=model.predict_category(estimate,0.5)

In [212]:
acc=model.accuracy(predicted, labels)

In [213]:
acc

1.0